//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creatorz_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SaleType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
